### ISSUE TITLE
Unable to initialize effect handler: RunAway: null

### ISSUE THREAD

**Issue by dEROZA** [L2J/L2J_DataPack#159]
2015.06.12 13:43:04,293	WARNING	1	com.l2jserver.gameserver.model.effects.AbstractEffect	AbstractEffect: Unable to initialize effect handler: RunAway: null

**Comment by Zoey76** [comment]
Fixed.

**Comment by dEROZA** [comment]
Can you tell me what it was?)

**Comment by luksdlt92** [comment]
@dEROZA this https://github.com/L2J/L2J_DataPack/commit/c4ab17ae225e80cd1d2d5da446544f921500f5b7
