### ISSUE TITLE
Freya bug quest

### ISSUE THREAD

**Issue by BioKryptY** [L2J/L2J_DataPack#180]
![shot00006](https://cloud.githubusercontent.com/assets/11686559/9535579/2aa03d16-4cf9-11e5-8bf6-a5721be36efc.jpg)
Don't teleport to Jinias guild when click in "Let me in!", bug in quest Acquisition of Divine Sword.

Please need fix urgent, thanks.

**Comment by luksdlt92** [comment]
It doens't happen to me.

**Comment by BioKryptY** [comment]
Thanks brother, I downloaded the clean datapack and it worked.

**Comment by luksdlt92** [comment]
:+1:
