### ISSUE TITLE
HTML commands are broken, placed in scripts folder

### ISSUE THREAD

**Issue by Sponer** [L2J/L2J_DataPack#189]
Hello, I have noticed a bug (maybe)..

for example all html files in html folder, listens to some html codes (like, a simple code <td cellspacing="x"> or <html noscrollbar> in advance)
but html files in scripts folder, are many many codes in html that doesn't work...
• html noscrollbar
• table align="x"
• td align="x"
• p
• pre
etc.

**Comment by Zoey76** [comment]
Post a HTML example.

**Comment by Sponer** [comment]
HTML window from scripts folder
![shot00000](https://cloud.githubusercontent.com/assets/7348928/10416243/ed96b9d6-7016-11e5-9e46-898574e3ec40.jpg)
HTML window from html folder
![shot00001](https://cloud.githubusercontent.com/assets/7348928/10416244/ed9a3a16-7016-11e5-820c-ec6d4c5931f2.jpg)

P.S. The p align="justify" command looks like it works outside of a table but not inside of it..

**Comment by Zoey76** [comment]
Thanks for the screen, please post the HTML example.

**Comment by Sponer** [comment]
html example:
[html noscrollbar]
[body]
[CODE....]
[/body]
[/html]

inside html folder: OK!
inside scripts folder: BUGGED!

(I put [] instead of <>)
