### ISSUE TITLE
Transformations scripts

### ISSUE THREAD

**Issue by DemICE** [L2J/L2J_DataPack#196]
I have some old high five files, and i could find the script for each transformation at this path---> \game\data\scripts\transformations
Example pic:
http://s18.postimg.org/hh1nq5cft/transformation_data.png

Apparently the current pack does not contain such a folder. i guessed it has been moved somewhere better, but i really cannot find it. 

Would appreciate any help

**Comment by Zoey76** [comment]
https://github.com/L2J/L2J_DataPack/tree/master/dist/game/data/stats/transformations

**Comment by DemICE** [comment]
oh they have been changed to xml format!  i see it has become a bit chaotic so things are harder to find but xmls are always good :P easy modification. nice 

thanks
