### ISSUE TITLE
Editing armor set base stat bonuses

### ISSUE THREAD

**Issue by DemICE** [L2J/L2J_DataPack#197]
Why would the game server care what base stat bonuses i want for my armorsets?

http://postimg.org/image/rdho79v6r/
http://postimg.org/image/si6mrzjdn/

**Comment by Zoey76** [comment]
Please post the XML on https://gist.github.com/

**Comment by DemICE** [comment]
https://gist.github.com/DemICE/c0c44a0b0e60733990b4

**Comment by Zoey76** [comment]
The order is defined in the XSD file: https://gist.github.com/Zoey76/a98313f1b04f28ce55b6
