### ISSUE TITLE
Improved Condition and Fresh Fruit Coctail

### ISSUE THREAD

**Issue by Pavel2451** [L2J/L2J_DataPack#199]
Hello,

Improved condition and Battle Roar is correct ? Because cannot be used Battle roar if improved condition buffed on character ?

Improved Con. and Fresh Coctail with Blessed Body. You can boost you character by doing this:
Buff with Fresh Fruit Coctail and later with Improved Condition, you will have more HP than normal...and both buffs are activate,

Just wrong type of skills..or effect or abnormal effect :)

**Comment by Zealar** [comment]
Fist report is not bug.
Second is invalid not happen for me. If can reproduce it post items/skill ID and current order with values.
