### ISSUE TITLE
Transformation Scrolls

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#237]
Like... Transformation Scroll: Death Blader, Transformation Scroll: Demon Prince, Transformation Scroll: Doll Blader, Transformation Scroll: Dragon Bomber don't work. Neither Transformation Scroll: Death Blader Event, Transformation Scroll: Demon Prince Event, Transformation Scroll: Doll Blader Event, Transformation Scroll: Dragon Bomber Event all other types of Transformation scrolls do not work neither.

**Comment by Zealar** [comment]
Working fine for me. Is that for H5 ? Give some item id.

**Comment by Sacrifice78** [comment]
itemId 20365 for example.

**Comment by Zealar** [comment]
Both 10132 and 20365 working for me.

**Comment by Sacrifice78** [comment]
I am referring to the scrolls that drops the treasure chest

**Comment by Sacrifice78** [comment]
Item:

<item id="20365" type="EtcItem" name="Transformation Scroll: Death Blader"> 		<set name="icon" val="BranchSys.icon.br_scroll_of_transformation_i00" /> 		<set name="default_action" val="SKILL_REDUCE" /> 		<set name="etcitem_type" val="SCROLL" /> 		<set name="material" val="PAPER" /> 		<set name="weight" val="120" /> 		<set name="is_tradable" val="false" /> 		<set name="is_dropable" val="false" /> 		<set name="is_sellable" val="false" /> 		<set name="is_stackable" val="true" /> 		<set name="is_premium" val="true" /> 		<set name="is_oly_restricted" val="true" /> 		<set name="is_freightable" val="true" /> 		<set name="handler" val="ItemSkills" /> 		<set name="item_skill" val="22046-1" /> 	</item>

And skill... for use with item

<skill id="22046" levels="1" name="Transformation Scroll: Doom Wraith"> 		<set name="abnormalLvl" val="26" /> 		<set name="abnormalTime" val="1800" /> 		<set name="abnormalType" val="TRANSFORM" /> 		<set name="blockedInOlympiad" val="true" /> 		<set name="icon" val="icon.skilltransform1" /> 		<set name="isMagic" val="2" />  		<set name="itemConsumeCount" val="1" /> 		<set name="itemConsumeId" val="20365" />  		<set name="magicLvl" val="-1" /> 		<set name="operateType" val="ACTIVE_CONTINUOUS" /> 		<set name="rideState" val="NONE;STRIDER;WYVERN;WOLF" /> 		<set name="targetType" val="SELF" /> 		<cond> 			<player canTransform="true" /> 		</cond> 		<for> 			<effect name="Transformation"> 				<param id="2" /> 			</effect> 		</for> 	</skill>

**Comment by Sacrifice78** [comment]
https://gist.github.com/Sacrifice78/f17073409e29676b0816

**Comment by Sacrifice78** [comment]
Its working perfect with my patch
