### ISSUE TITLE
Retail-like quest Q00503_PursuitOfClanAmbition (503)

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#240]
WITCH_KALIS = 30759 and WITCH_ATHREA = 30758 are blinking on world (despawn 60 seconds, spawn 5 seconds and in a loop).
case "SPAWN_WITCH":
			{
				addSpawn(WITCH_ATHREA, 160688, 21296, -3714, 0, false, 5000);
				addSpawn(WITCH_KALIS, 160690, 21176, -3712, 0, false, 5000);
				break;
			}
fix 5000 (5 seconds) in both sentences

**Comment by Sacrifice78** [comment]
it's 90000 no 5000

**Comment by Sacrifice78** [comment]
https://gist.github.com/Sacrifice78/329b658ec6415426de12

**Comment by ivantotov** [comment]
I will  Fix UUU
Check Retail Then SPAM
