### ISSUE TITLE
Fixed one typo on Rabbits

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#245]
### Eclipse Workspace Patch 1.0
#P L2J_DataPack
diff --git dist/game/data/scripts/custom/events/Rabbits/Rabbits.java dist/game/data/scripts/custom/events/Rabbits/Rabbits.java
index 8232152..15c660e 100644
--- dist/game/data/scripts/custom/events/Rabbits/Rabbits.java
+++ dist/game/data/scripts/custom/events/Rabbits/Rabbits.java
@@ -118,7 +118,7 @@
 		// Announce event start
 		Broadcast.toAllOnlinePlayers("Rabbits Event: Chests spawned!");
 		Broadcast.toAllOnlinePlayers("Rabbits Event: Go to Fantasy Isle and grab some rewards!");
-		Broadcast.toAllOnlinePlayers("Rabbits Event: You have " + EVENT_TIME + " minuntes!");
+		Broadcast.toAllOnlinePlayers("Rabbits Event: You have " + EVENT_TIME + " minutes!");
 		Broadcast.toAllOnlinePlayers("Rabbits Event: After that time all chests will disappear...");
 		// Schedule event end
 		startQuestTimer("END_RABBITS_EVENT", EVENT_TIME * 60000, null, eventMaker);
@@ -273,4 +273,4 @@
 	{
 		new Rabbits();
 	}
-}
+}
\ No newline at end of file

**Comment by Zoey76** [comment]
Please use Gist or send us a Pull Request.

**Comment by Sacrifice78** [comment]
Yes, that's here. Sorry.
https://gist.github.com/Sacrifice78/347261a7c7f9f07c8e35
