### ISSUE TITLE
Skill Fake Death skill id="60"

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#247]
When you use it first time works, but when you try to stand up, you dye one more time, removes 200MP and stay in flat. If you press again the toggle skill then stand up. It's something rare no more that need to fix.

**Comment by Sacrifice78** [comment]
Must be a toggle "DA1" or should be active skill "A1" ????

**Comment by Sacrifice78** [comment]
Ok pressing sit/stand button or well command /stand... close if are so.

**Comment by Zealar** [comment]
Fixed https://github.com/L2J/L2J_Server/commit/999a80af4dc0e1a873230d3bf60b8198e0ff82cf
