### ISSUE TITLE
BattleRoar

### ISSUE THREAD

**Issue by Tavo22** [L2J/L2J_DataPack#251]
Skill id : 121
When you have a buff that gives you HP and has a greater effect level than the skill it should heal you. Currently is not healing the active character.

**Comment by Zoey76** [comment]
Please post a retail video or source where is is working like you describe.

**Comment by Tavo22** [comment]
Ok, let me see.

**Comment by ovalefor** [comment]
What happens and when you buff with, say, Bless the Body Lv6 and uses the Battle Roar Level 5, HP does not regenerate as in the description, only regenerates if the same level of Bless the Body or other skill Max HP. (Sorry for the english)

**Comment by Zealar** [comment]
OMG again with that? From how much time do you play l2? That one is discuss million times google it.

**Comment by Zoey76** [comment]
http://www.l2jserver.com/forum/viewtopic.php?f=103&t=28046&hilit=Battle+Roar
