### ISSUE TITLE
Q00503_PursuitOfClanAmbition

### ISSUE THREAD

**Issue by Tavo22** [L2J/L2J_DataPack#258]
The quest is despawning npc id 30759 that is used for other quests like Q00241_PossessorOfAPreciousSoul1.

**Comment by ivantotov** [comment]
1 - Quest spawn this npc  with delay 5  second
2 - After 5 seconds  despawn npc
3 - I dont see this npc in quest 241

**Comment by Tavo22** [comment]
True, my mistake. It is on quest Q00242_PossessorOfAPreciousSoul2

**Comment by ivantotov** [comment]
And What is the problem ?
Quest spawn and Quest despawn.
This npc use also in Quest 501

**Comment by Tavo22** [comment]
You can not continue quest 242 because the npc is not there, it was despawned by quest 503. Try to spawn it with a gm character and after 5 seconds is despawned again.

**Comment by ivantotov** [comment]
Ok  we will check 

Tnx

**Comment by Sacrifice78** [comment]
@ivantotov i told you few weeks ago that anything extrange happend with this issue. You dont want to listen yet.

**Comment by Sacrifice78** [comment]
https://github.com/L2J/L2J_DataPack/issues/240

**Comment by ivantotov** [comment]
Sacrifice78  you said nonsense 
you do delay spawn 90000
Stop spam  all post when you don't know what do code

**Comment by Sacrifice78** [comment]
Previously it was well and you've put so. That was how it was when it was when the quest was Jython. I will not argue with you, I do not have time for that. I leave here as it was for you to think.

https://gist.github.com/Sacrifice78/17073aa44f6f3c2ed32d

**Comment by ivantotov** [comment]
Jython is wrong

**Comment by ivantotov** [comment]
Fix
Thanks  for report: Tavo22
