### ISSUE TITLE
Fake Death

### ISSUE THREAD

**Issue by Tavo22** [L2J/L2J_DataPack#260]
Skill id: 60
You should be able to stand from the ground using the same skill. On the latest revision the only way to stand up is with the sit/stand button.

**Comment by Zoey76** [comment]
Where have you tested?

**Comment by valanths1990** [comment]
invalid in retail (rpg-club) you can only stop fake death with /stand 
otherwise you get message you cannot move while sitting if you press it again

**Comment by Zealar** [comment]
On fake dead players cannot use ANY skill not just fake death.

**Comment by Zoey76** [comment]
http://www.l2jserver.com/forum/viewtopic.php?f=103&t=27792&p=165280&hilit=Fake+Death#p165253
