### ISSUE TITLE
Trap Skills

### ISSUE THREAD

**Issue by facheme** [L2J/L2J_DataPack#266]
The Trickster should be able to put one trap of each type. However, currently, you can only put 1. If you try to put something other, clears the first.

- flash trap
- fire trap
- poison trap
- Oblivion trap
- slow trap

**Comment by Zealar** [comment]
Trickster can have only 1 trap no matter of type.

**Comment by Zoey76** [comment]
@facheme this reports are from players or from your own experience in retail/L2Off servers?
