### ISSUE TITLE
DispelBySlotProbability

### ISSUE THREAD

**Issue by valanths1990** [L2J/L2J_DataPack#272]
http://prntscr.com/9f3qww

you split stack effect by effect,lvl but there is no level to split

**Comment by Zealar** [comment]
DispelBySlotProbability ignore level and remove all of them. But there is just option to add them if you want, like custom option not a bug.

**Comment by valanths1990** [comment]
You split it but you dont use it
even if you add it in xml it will use max short value anyway

http://prntscr.com/9fly61
