### ISSUE TITLE
Monster's stats

### ISSUE THREAD

**Issue by rizaar** [L2J/L2J_DataPack#275]
Hello,
I have noticed that an important part of monsters have unacurate stats. That's flagrant on HP stat. 
i know there's a calculation on the stat hp in xml, but when a make calcules and check in game, the values i found *(in game and on my sheet are the same)* are not the same that informations i can found on severals db, eaven L2wiki in the write revision of the monster *(you can choose wich revision you want on the left of the searchbar)*

The main exemple i can point to you for bright this probleme is Nephilim royal garde: 
http://l2db.info/high-five/npcs/21205 
here, the database indicate 2676 \*4 = 10704
http://l2.dropspoil.com/npc/21205/nephilim-royal-guard.html here, that indicate 3742 \* 4 = 11226
http://base.l2j.ru/index.php?p=1&id=21205 here 10707 hp
http://www.lineage-realm.com/eng/dropcalculator/npc/21205/Nephilim-Royal-Guard here 2677 \* 4= 10708
but in source code we have a hpbase: 2676.65854
[Xml of the monster: ID 21205](https://github.com/L2J/L2J_DataPack/blob/develop/dist/game/data/stats/npcs/21200-21299.xml)
and we have <sNpcPropHpRate>4</sNpcPropHpRate> so that make 2676.65854 * 4 = 10706.63416
we'r near the stats linked with sources, but not done yet.
[The CON (con="43")bonus](https://github.com/L2J/L2J_DataPack/blob/develop/dist/game/data/stats/statBonus.xml)
)  is applied and that gave us  10706.63416 * 1.58 = 16916,4819728
that match with ingame stats: 
[ingame Stats](http://img11.hostingpics.net/pics/213679Shot00000.png)
witch is way too far from the sources i can find.

In my opinion, i think the CON bonus have been skiped for the calculation of base hp that induce a error in recalculation by the computer after. 

i don't review p.atk def and other stats but they'r way too hight from the stats i can find.  

Sorry for my english, i'm not a native speaker.

**Comment by Zealar** [comment]
Only program with stats is evasion/acc formula but stats is ok.Most of source you look is wrong or show hp after some calculations or without any.
So for calculate proper in game hp you need to apply bonus from con/xhp/passives.
Look here http://base.rpg-club.com/#db.monster.main.21205#
They use base * con bonus but not apply xHP so.
4229 * 4 = 16916
