### ISSUE TITLE
Quest Fates Whisper Bug Html

### ISSUE THREAD

**Issue by u3games** [L2J/L2J_DataPack#291]
Last rev....

![photo_2016-01-11_18-50-47](https://cloud.githubusercontent.com/assets/5102409/12241589/5b435f96-b894-11e5-891e-79e4d7f8665d.jpg)

**Comment by Sacrifice78** [comment]
https://github.com/L2J/L2J_DataPack/commit/b4dbd36f33f67fe5b87d8ac8c2771b694b9f0771

**Comment by Zoey76** [comment]
Fixed in https://github.com/L2J/L2J_DataPack/commit/1201b67f9258536f3c8631d29e2120d1a6e13c88
