### ISSUE TITLE
Chain Heal

### ISSUE THREAD

**Issue by ovalefor** [L2J/L2J_DataPack#293]
The skill Chain Heal is catching on NPCs, Players that are not in the party or clan and NPCs during the siege, recovering their HP.

**Comment by u3games** [comment]
confirm

**Comment by Sacrifice78** [comment]
Confirmed... apply to GM Characters too if are near.

**Comment by Sacrifice78** [comment]
skillId 1553

**Comment by Sacrifice78** [comment]
game/data/scripts/handlers/targethandlers/AreaFriendly.java
checkTarget method
Line 110
