### ISSUE TITLE
Exception in thread "AISTPool-3" java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_DataPack#296]
![dibujo](https://cloud.githubusercontent.com/assets/13767243/12271368/e446a08e-b95a-11e5-9dd5-b4a75773d3f2.jpg)

**Comment by Sacrifice78** [comment]
This issue is for core. Sorry my error.

**Comment by Zoey76** [comment]
Fixed in https://github.com/L2J/L2J_Server/commit/d1c4e8b6be12dad3b6c49887d86aed302c813e13
