### ISSUE TITLE
Prime Shop DataPack Side

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#302]
It's missing...

**Comment by Zoey76** [comment]
Since NA client doesn't support it, it's unlikely that we will be adding it anytime soon.

**Comment by Sacrifice78** [comment]
You say that because you have to edit the client (default is not enabled PrimeShop) ... no?

**Comment by Zoey76** [comment]
Yes.

**Comment by Sacrifice78** [comment]
https://github.com/L2J/L2J_Server/issues/224#issuecomment-198663207
