### ISSUE TITLE
Character locked

### ISSUE THREAD

**Issue by u3games** [L2J/L2J_DataPack#309]
# Summary

When a player is in flag mode + target to a raid boss + use skill reinforcement --> BUG CLIENT!

# How to reproduce 

1.- No flag + target raid + buff skill reinforcement --> no bug (not locked).
2.- Mode flag + target raid + buff skill reinforcement --> bug (locked).

- If char magicians use skill, nothing happens.
- If the warriors used skills (all skill), there is a rate of getting bug. And all warrior char is locked ! (only warriors).
-  It only happens when you fight raids boss, in pvp no bug.

NOTE: If party use skill type "Pain of Shilen" or "Spirit of Phoenix", all warriors in mode flag is locked. With Combat Aura no bug.... no affect. 

# VIDEO

1- Player --> https://youtu.be/KkUFShHRAWY

**Comment by Zealar** [comment]
Is there way to be reproduced on local?

**Comment by u3games** [comment]
Yes, i test this.. and new report:

Go to kill "Ember Boss" in party (3 mages + 4 warrriors).

- If magicians use skill, nothing happens.
- If the warriors used skills (all skill), there is a rate of getting bug. And all warrior char is locked ! (only warrios).

- GM char no bug.
- It only happens when you fight raids boss, in pvp no bug.

**Comment by Zealar** [comment]
What if there is no mages?
What if got follow chars
PlayerA = Titan (no skill just normal hits)
PlayerB = Gladiator (skills)
PlayerC = Paladin
When player C use Spirit of Phoenix all chars will stuck or just Gladiator and Paladin? What if in moment of Spirit of PHoenix cast there is no skill usage?

**Comment by u3games** [comment]
If only warriors char in party, all locked...

It is to make any attack skill (all skill attack in warrior char).

**Comment by u3games** [comment]
I test now this... and look the bug.

https://youtu.be/KkUFShHRAWY

1.- No flag + target raid + buff skill reinforcement --> no bug (not locked).
2.- mode flag + target raid + buff skill reinforcement --> bug (locked).

NOTE: If party use skill type "Pain of Shilen" or "Spirit of Phoenix", all warriors in mode flag is locked.

**Comment by Zealar** [comment]
So that need to happen with Combat Aura to. Is lock all chars or just flag one?

**Comment by u3games** [comment]
no, with Combat Aura no bug.... no affect.

**Comment by u3games** [comment]
FUCK! Error in my private dev... sorry. 

Close.
