### ISSUE TITLE
Summon Shadow - passive Skill

### ISSUE THREAD

**Issue by l2toplist** [L2J/L2J_DataPack#318]
Skill id 4233 - Vampiric attack, not work.
This is passive skill for summon - shadow.

**Comment by Zealar** [comment]
Is working perfect. Maybe attack town npc what got HP drop to zero. Try to heal npc till pet hit.

**Comment by l2toplist** [comment]
work for monster, not work for shadow.
This skill work for character, not work for shadow.
Shadow regen hp, not absorbDmg i am test val=150.

**Comment by Zealar** [comment]
Where do you say interlude?
Current only H5 got support. We don't have that much devs to support interlude too. But seems that problem is fixed in h5 so look in code where and how is fixed.

**Comment by l2toplist** [comment]
I try, but no work, please help.
Interlude the best of the best! Forever.

**Comment by Zealar** [comment]
Follow this steps and each need to be OK before go to next.
1) Check if that skill enter in pet skill list
2) Check pet stats about absorb dmg
3) Look in code why absorb dmg don't recover HP on hit (need to be near dmg message)

**Comment by l2toplist** [comment]
> 1) Check if that skill enter in pet skill list
ok
>2) Check pet stats about absorb dmg
What do you mean? How exactly to check it?
> 3) Look in code why absorb dmg don't recover HP on hit (need to be near dmg message)
`
// Absorb HP from the damage inflicted
					double absorbPercent = getStat().calcStat(Stats.ABSORB_DAMAGE_PERCENT, 0, null, null);
					
					if (absorbPercent > 0)
					{
						int maxCanAbsorb = (int) (getMaxHp() - getCurrentHp());
						int absorbDamage = (int) ((absorbPercent / 100.) * damage);
						
						if (absorbDamage > maxCanAbsorb)
						{
							absorbDamage = maxCanAbsorb; // Can't absord more than max hp
						}
						
						if (absorbDamage > 0)
						{
							setCurrentHp(getCurrentHp() + absorbDamage);
							
							// Custom messages - nice but also more network load
							/*
							 * if (this instanceof L2PcInstance) ((L2PcInstance)this).sendMessage("You absorbed " + absorbDamage + " damage."); else if (this instanceof L2Summon) ((L2Summon)this).getOwner().sendMessage("Summon absorbed " + absorbDamage + " damage."); else if (Config.DEBUG)
							 * _log.info(getName() + " absorbed " + absorbDamage + " damage.");
							 */
						}
					}
`
You mean it?

**Comment by l2toplist** [comment]
Shadow is no reaction any stats... Shadow is npcskills or pet skills?
