### ISSUE TITLE
[Priority 3][Develop] Forgotten Song of Wind Storm

### ISSUE THREAD

**Issue by gajet5** [L2J/L2J_DataPack#320]
[DataBase RU](http://hf5.l2central.info/%D0%9F%D0%B5%D1%81%D0%BD%D1%8F_%D0%A8%D1%82%D0%BE%D1%80%D0%BC%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%92%D0%B5%D1%82%D1%80%D0%B0_-_%D0%92%D0%B8%D1%80%D1%82%D1%83%D0%BE%D0%B7)

**In L2J_DataPack\dist\game\data\skillTrees\classSkillTree.xml**
`<skill skillName="Song of Wind Storm" skillId="764" skillLvl="1" getLevel="76" levelUpSp="8330000" learnedByNpc="true" />`

**Comment by Zealar** [comment]
`	
	<skillTree type="classSkillTree" classId="100">
		<skill skillName="Song of Wind Storm" skillId="764" skillLvl="1" getLevel="76" learnedByFS="true" />`

Is learn by scroll not from npc.

**Comment by gajet5** [comment]
I'm sorry, I did not see.
